#pragma once
#include <map>
#include <functional>
#include "Actor.h"
#include "Map.h"
#include "FileDirectory.h"
#include "GameData.h"

//null resources
const int nullId = -1;
const chtype nullSymbol = 'X' | COLOR_RED_BOLD << TEXTCOLOR_OFFSET;
const std::string nullName = "-";

class ResourceManager
{
private:
	int getColor(char c);

public:
	std::map<std::string, Actor, std::function<bool(std::string, std::string)> > actors;
	std::map<int, Map> gameMaps;
	GameData theData;

	std::vector<Actor*> playerParty;


	ResourceManager();
	
	/*Load one resource of each type to be used in the absence of other needed resources. 
	These resources are generated by the program and do not live on the hard drive.*/
	void loadNullResources();

	/*Load Actors from text file. Returns the count of Actors loaded.*/
	int loadActorsFromTextFile(std::ifstream& textFile);

	/*Load Maps from separate data files in one directory. Returns the count of Maps loaded.*/
	int loadGameMapsFromDir(FileDirectory& dir);


};
